urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', 'athena.front.index.index'),
    url(r'^about/$', 'athena.front.index.about'),
    url(r'^register/$', 'athena.users.views.register'),
    url(r'^logout/$', 'athena.users.views.logout'),
    url(r'^admin-login/$', 'athena.radmin.login_view.login'),
    url(r'^profile/$', 'athena.users.views.profile'),
    url(r'^login/$', 'athena.users.views.login'),
    url(r'^login/demo/$', 'athena.users.views.demo'),

    (r'^media/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': 'D:/projects/athena/media/'}),  
    (r'^uploads/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': 'D:/projects/athena/uploads/'}),  
)

urlpatterns += patterns('athena.rstudent',
    url(r'^demo/start/(?P<test_id>\d+)/$', 'demo.start_demo_exam'),
    url(r'^past/$', 'protocol.index'),
    url(r'^past/(?P<protocol_id>\d+)/$', 'protocol.index'),
    url(r'^groups/$', 'views.groups'),
    url(r'^groups/join/$', 'views.join_group'),    
)

urlpatterns += patterns('athena.tests',
    url(r'^test/ajax/$', 'views.ajax'),
    url(r'^test/$', 'views.test'),
)

urlpatterns += patterns('athena.rteacher',

    url(r'^teacher/groups/$', 'manage_groups.list'),
    url(r'^teacher/groups/(?P<group_id>\d+)/$', 'manage_groups.group'),
    url(r'^teacher/groups/(?P<group_id>\d+)/members/$', 'manage_groups.members'),
    url(r'^teacher/groups/(?P<group_id>\d+)/requests/$', 'manage_groups.requests'),
    url(r'^teacher/groups/create/$', 'manage_groups.create'),

        # must be called with POST to actually succeed. Calling with GET will result in HTTP 400
    url(r'^teacher/groups/(?P<group_id>\d+)/delete/$', 'manage_groups.delete'),

    url(r'^teacher/exams/protocol/(?P<testresult_id>\d+)/$', 'term_supervise.protocol'),
    url(r'^teacher/exams/(?P<exam_id>\d+)/terms/(?P<term_id>\d+)/supervise/$', 'term_supervise.supervise'),
    url(r'^teacher/exams/(?P<exam_id>\d+)/terms/(?P<term_id>\d+)/supervise/ajax/$', 'term_supervise.ajax'),
    url(r'^teacher/exams/(?P<exam_id>\d+)/terms/(?P<term_id>\d+)/setup/ajax/$', 'term_setup.setup_ajax'),
    url(r'^teacher/exams/(?P<exam_id>\d+)/terms/(?P<term_id>\d+)/setup/$', 'term_setup.setup'),
    url(r'^teacher/exams/(?P<exam_id>\d+)/terms/(?P<term_id>\d+)/delete/$', 'manage_exams.delete_term'),
    url(r'^teacher/exams/(?P<exam_id>\d+)/terms/(?P<term_id>\d+)/$', 'manage_exams.term'),
    url(r'^teacher/exams/table/(?P<exam_id>\d+)/$', 'gentable.gentable'),
    url(r'^teacher/exams/$', 'manage_exams.list'),
    url(r'^teacher/exams/create/$', 'manage_exams.create'),
    url(r'^teacher/exams/(?P<exam_id>\d+)/$', 'manage_exams.exam'),
    url(r'^teacher/exams/(?P<exam_id>\d+)/addterm/$', 'manage_exams.addterm'),

        # must be called with POST to actually succeed. Calling with GET will result in HTTP 400
    url(r'^teacher/exams/(?P<exam_id>\d+)/delete/$', 'manage_exams.delete'),

    url(r'^teacher/tests/$', 'tests.list'),
    url(r'^teacher/tests/create/$', 'tests.create'),
    url(r'^teacher/tests/(?P<test_id>\d+)/$', 'tests.test'),
    url(r'^teacher/tests/(?P<test_id>\d+)/delete/$', 'tests.delete_test'),
    url(r'^teacher/tests/(?P<test_id>\d+)/ajax/$', 'tests.test_ajax'),
    url(r'^teacher/tests/(?P<test_id>\d+)/category/create/$', 'tests.create_category'),
    url(r'^teacher/tests/(?P<test_id>\d+)/category/(?P<category_id>\d+)/$', 'tests.category'),
    url(r'^teacher/tests/(?P<test_id>\d+)/category/(?P<category_id>\d+)/delete/$', 'tests.delete_category'),

    url(r'^teacher/tests/(?P<test_id>\d+)/category/(?P<category_id>\d+)/question/new/$', 'tests.create_question'),
    url(r'^teacher/tests/(?P<test_id>\d+)/category/(?P<category_id>\d+)/question/(?P<question_id>\d+)/$', 'tests.question'),
)


urlpatterns += patterns('athena.radmin',

    url(r'^admin/accounts/$', 'manage_accounts.list'),
    url(r'^admin/accounts/(?P<account_id>\d+)/$', 'manage_accounts.account'),

    url(r'^admin/accounts/create/$', 'manage_accounts.create'),

    url(r'^admin/accounts/students/$', 'manage_accounts.view_students'),
    url(r'^admin/accounts/students/(?P<page>\d+)/$', 'manage_accounts.view_students'),

        # must be called with POST to actually succeed. Calling with GET will result in HTTP 400
    url(r'^admin/accounts/(?P<account_id>\d+)/delete/$', 'manage_accounts.delete'),
    url(r'^admin/accounts/(?P<account_id>\d+)/reset_pwd/$', 'manage_accounts.reset_pwd'),
    url(r'^admin/accounts/(?P<account_id>\d+)/su/$', 'manage_accounts.su'),
)

rteacher/models.py
# coding=UTF-8
from django.db import models
from hashlib import sha1
from athena.users.models import User
from athena.tests.models import Test

class Group(models.Model):
    teacher = models.ForeignKey(User, related_name='groups_owned')
    name = models.CharField(max_length=30, verbose_name=u'Nazwa')
    description = models.TextField(blank=True, verbose_name=u'Opis')
    is_archival = models.BooleanField(verbose_name=u'Archiwalna?', default=False)
    students = models.ManyToManyField(User)

    created_on = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_on']

    def __unicode__(self):
        return self.name
    
    @staticmethod
    def get_demo_group():
        """All demo accounts belong to this group"""
        return Group.objects.get(id=1)
        

class JoinRequest(models.Model):
    """A request for teacher to add a student to a group"""
    student = models.ForeignKey(User)
    group = models.ForeignKey(Group)

    reason = models.TextField()

    created_on = models.DateTimeField(auto_now=True)

    def execute(self):
        """Joins the target group. Removes this instance"""
        self.group.students.add(self.student)
        self.delete()

class Exam(models.Model):
    test = models.ForeignKey(Test, verbose_name=u'Wzór testu')
    group = models.ForeignKey(Group, verbose_name=u'Grupa')
    name = models.CharField(max_length=50, verbose_name=u'Nazwa')
    created_on = models.DateTimeField(auto_now=True)
    owner = models.ForeignKey(User, verbose_name='Właściciel')

    class Meta:
        ordering = ['-created_on']

    def is_open(self):
        """Returns whether there is at least one open term"""
        terms = self.term_set.all().only('is_closed')
        for term in terms:
            if not term.is_closed:
                return True
        return False

    def get_passing_testresults(self):
        """Returns an list of all testresults objects from all terms"""
        a = []
        for tres in [term.get_passing_testresults() for term in self.term_set.all()]:
            a.extend(list(tres))
        return a

class Term(models.Model):
    exam = models.ForeignKey(Exam)
    name = models.CharField(max_length=50, verbose_name=u'Nazwa')

    term_time = models.DateTimeField(verbose_name=u'Termin')

    is_closed = models.BooleanField(default=False)
    is_progressing = models.BooleanField(default=False)

    class Meta:
        ordering = ['-term_time']

    def get_passing_testresults(self):
        """Returns an iterator of tests.models.TestResult of students
        that have passed this term"""
        return self.testresult_set.filter(grade__gte=3, is_invalidated=False, is_killed=False)

rteacher/views.py
from athena.users import must_be_teacher
from athena.core import render_to_response

@must_be_teacher
def index(request):
    return render_to_response('rteacher/index.html', request)

templates/rteacher/gentable.html
<!DOCTYPE html>
<html>
<head>
    <title>Tabela zdawań {{ exam.name }}</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <style type="text/css">
        table { border-collapse: collapse; border: 1px solid black; }
        td, th { padding: 5px 5px 5px 5px; border: 1px solid black; }
        th { font-weight: bold; }
    </style>
</head>
<body>
<h1>Tabela zdawań {{ exam.name }}</h1>
<table>
    <tr>
        <th></th>
        {% for term in terms %}
            <th>{{ term.name }}<br>{{ term.term_time|date:"d-m-Y H:i" }}</th>
        {% endfor %}
    </tr>
    {% for surname, name, number, grades in xtab %}
    <tr>
        <td>{{ surname }} {{ name }} {{ number }}</td>
        {% for grade in grades %}<td>{{ grade|default_if_none:"" }}</td>{% endfor %}
    </tr>
    {% endfor %}
</table>
</body>
</html>

templates/rteacher/manage_exams_add.html
{% extends "rteacher/manage_exams_list.html" %}

{% block title %}Dodaj nowy egzamin{% endblock %}

{% block layout_rightside %}
    <h1>Utwórz nowy egzamin</h1>
    <form action="/teacher/exams/create/" method="post">
        {{ form.as_p }}
        <input type="submit" value="Utwórz">
    </form>

{% endblock %}

templates/rteacher/manage_exams_addterm.html
{% extends "rteacher/manage_exams_list.html" %}

{% block title %}Dodaj termin - {{ exam.name }}{% endblock %}

{% block layout_head %}
<script type="text/javascript" src="/media/js/jquery-ui-1.10.4.custom.min.js"></script>
<link rel="stylesheet" type="text/css" href="/media/css/jquery-ui-1.10.4.custom.min.css">
<script type="text/javascript"> $(function() {
    $("#id_term_time").datetimepicker();
  });</script>

{% endblock %}

{% block layout_rightside %}
    <h1>Utwórz nowy termin do egzaminu {{ exam.name }}</h1>
    <form action="/teacher/exams/{{ exam.id }}/addterm/" method="post">
        {{ form.as_p }}
        <input type="submit" value="Utwórz">
    </form>
{% endblock %}

templates/rteacher/manage_exams_exam.html
{% extends "rteacher/manage_exams_list.html" %}

{% block layout_head %}
<style type="text/css">
    th { font-weight: bold; }
    table { text-align: center; margin-bottom: 20px; }
    td, th { padding-right: 10px; }
</style>
{% endblock %}

{% block title %}Zarządzanie - {{ exam.name }}{% endblock %}

{% block layout_rightside %}
    <form action="/teacher/exams/{{ exam.id }}/" method="post">
        {{ form.as_p }}
        <input type="submit" value="Zapisz">
    </form>

    <div style="margin: 10px 0px 20px 30px;">

        <table>
            <tr><th>Nazwa</th><th>Data</th><th>Stan</th></tr>
            {% for term in exam.term_set.all %}
                <tr>
                    <td><a href="/teacher/exams/{{ exam.id }}/terms/{{ term.id }}/">{{ term.name }}</a></td>
                    <td>{{ term.term_time|date:"d-m-Y H:i" }}</td>
                    <td>
                        {% if term.is_closed %}
                            Zakończony
                        {% else %}
                            {% if term.is_progressing %}
                                W trakcie
                            {% else %}
                                Oczekujący
                            {% endif %}
                        {% endif %}
                </tr>
            {% endfor %}
        </table>

        <a href="/teacher/exams/{{ exam.id }}/addterm/">Dodaj termin</a>
    </div>

    <form action="/teacher/exams/{{ exam.id }}/delete/" method="post" class="ml30">
        <input type="submit" value="Usuń egzamin">
    </form>

    <a style="margin-left: 30px;" href="/teacher/exams/table/{{ exam.id }}/" target="_blank">Tabela zdawań</a>
{% endblock %}

templates/rteacher/manage_exams_list.html
{% extends "base-layout.html" %}

{% block title %}Lista egzaminów{% endblock %}

{% block layout_head %}
{% endblock %}

{% block layout_entries %}
    <li><a href="/profile/">Profil</a></li>
    <li><a href="/teacher/groups/">Grupy</a></li>
    <li class="current"><a href="/teacher/exams/">Egzaminy</a></li>
    <li><a href="/teacher/tests/">Baza testów</a></li>
{% endblock %}

{% block layout_content %}
    {% if exam %}
        <h1><a href="/teacher/exams/{{ exam.id }}/">{{ exam.name }}</a></h1>
        <hr>
    {% endif %}

<div id="base_leftside">
    {% if selected_exam_id == 'create' %}
        Dodaj nową grupę
    {% else %}
        <a href="/teacher/exams/create/">Dodaj nowy egzamin</a>
    {% endif %}


<h1 style="margin-top: 20px;">Egzaminy</h1>
<p>
    {% for exam in exams %}
        {% if exam.id == selected_exam_id %}
            {{ exam.name }} ({{ exam.term_set.count }} terminów)
        {% else %}
            <a href="/teacher/exams/{{ exam.id }}/">{{ exam.name }}</a> 
            ({{ exam.term_set.count }} terminów)        
        {% endif %}<br>
    {% empty %}
        brak
    {% endfor %}
</p>
<div style="margin-bottom: 20px;"></div>
</div>
<div id="base_rightside">
    {% block layout_rightside %}{% endblock %}
</div>
{% endblock %}

templates/rteacher/manage_exams_term.html
{% extends "rteacher/manage_exams_list.html" %}

{% block layout_head %}
<style type="text/css">
    th { font-weight: bold; }
    table { text-align: center; margin-bottom: 20px; }
    td, th { padding-right: 10px; }
</style>
<script type="text/javascript" src="/media/js/jquery-ui-1.10.4.custom.min.js"></script>
<link rel="stylesheet" type="text/css" href="/media/css/jquery-ui-1.10.4.custom.min.css">
<script type="text/javascript"> $(function() {
    $("#id_term_time").datetimepicker();
  });</script>
{% endblock %}

{% block title %}Zarządzanie - {{ exam.name }}{% endblock %}

{% block layout_rightside %}
    <form action="/teacher/exams/{{ exam.id }}/" method="post">
        {{ form.as_p }}
        <input type="submit" value="Zapisz">
    </form>

    <div style="margin: 10px 0px 20px 30px;">

        Stan: 
        {% if term.is_closed %}
            <span style="font-weight: bold;">Zamknięty</span><br>
            Oznacza to że uczestnicy nie mogą już uczestniczyć w tym terminie. Wyniki można obejrzeć  <a href="/teacher/exams/{{ exam.id}}/terms/{{ term.id }}/supervise/">w opcji nadzorowania terminu</a>.
        {% elif term.is_progressing %}
            <span style="font-weight: bold;">W trakcie</span><br>
            Oznacza to że uczestnicy są w trakcie pisania egzaminu. Postęp można obserwować <a href="/teacher/exams/{{ exam.id}}/terms/{{ term.id }}/supervise/">poprzez opcję nadzorownia terminu</a>
        {% else %}
            <span style="font-weight: bold;">Oczekujący</span><br>
            Termin oczekuje aż uczestnicy zostaną określeni przez nauczyciela i uruchomiony zostanie egzamin w tym terminie. Można to uczynić <a href="/teacher/exams/{{ exam.id }}/terms/{{ term.id }}/setup/">poprzez opcję uruchamiania terminu</a>.
        {% endif %}
    </div>

    <form action="/teacher/exams/{{ exam.id }}/terms/{{ term.id }}/delete/" method="post" class="ml30">
        <input type="submit" value="Usuń termin">
    </form>
{% endblock %}

templates/rteacher/manage_groups_members.html
{% extends "rteacher/manage_groups_list.html" %}

{% block title %}Grupa {{ group.name }} - lista członków{% endblock %}

{% block layout_rightside %}
<h1>Grupa {{ group.name }} - członkowie</h1>
    <table>
        <tr>
            <th style="width: 200px;">Imię i nazwisko</th>
            <th>Nr albumu</th>
            <th></th>
        </tr>
    {% for member in group.students.all %}
        <tr>
            <td>{{ member.name }} {{ member.surname }}</td>
            <td>{{ member.number }}</td>
            <td>
                <form action="/teacher/groups/{{ group.id }}/members/" method="post">
                    <input type="hidden" name="user_id" value="{{ member.id }}">
                    <input type="submit" value="Usuń">
                </form>
            </td>
        </tr>
    {% endfor %}
</table>
<div style="margin-bottom: 20px;"></div>
{% endblock %}

templates/rteacher/manage_groups_requests.html
{% extends "rteacher/manage_groups_list.html" %}

{% block title %}Grupa {{ group.name }} - lista członków{% endblock %}

{% block layout_head %}
<style type="text/css">
    .name { font-size: 1.2em; }
    .number { font-size: 1.1em; }
    .date { font-size: 0.8em; }
    p div { margin: 3px 0px 3px 0px; }
</style>
{% endblock %}

{% block layout_entries %}
    <li><a href="/profile/">Profil</a></li>
    <li class="current"><a href="/teacher/groups/">Grupy</a></li>
    <li><a href="/teacher/exams/">Egzaminy</a></li>
    <li><a href="/teacher/tests/">Baza testów</a></li>
{% endblock %}

{% block layout_rightside %}
<h1>Grupa {{ group.name }} - wnioski</h1>
    {% for jr in group.joinrequest_set.all %}
    <p>
        <div class="name">{{ jr.student.name }} {{ jr.student.surname }}</div>
        <div class="number">{{ jr.student.number }}</div>
        <div>{{ jr.reason|linebreaksbr }}</div>
        <div class="date">Złożono {{ jr.created_on }}</div>

        <form class="standalone-button" action="/teacher/groups/{{ group.id }}/requests/" method="post"><input type="hidden" name="request_id" value="{{ jr.id }}"><input type="hidden" name="action" value="confirm"><input type="submit" value="Zatwierdź"></form></td>
        <form class="standalone-button" action="/teacher/groups/{{ group.id }}/requests/" method="post"><input type="hidden" name="request_id" value="{{ jr.id }}"><input type="hidden" name="action" value="delete"><input type="submit" value="Usuń"></form></td>
    </p>
    <hr>
    {% endfor %}
</table>
<div style="margin-bottom: 20px;"></div>
{% endblock %}

templates/rteacher/protocol.html
<!DOCTYPE html>
<html>
<head>
    <title>Protokół zdawania nr {{ testresult.id }}</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <style type="text/css">
        .str { font-weight: bold; }
        .answers { margin-left: 30px; }
        .footnote { font-size: 0.8em; }
        .sepa { margin-top: 20px; }
    </style>
</head>
<body>
    <h1>Protokół zdawania nr {{ testresult.id }}</h1>
    <p>
        Zdający: <span class="str">{{ testresult.written_by.name }} {{ testresult.written_by.surname }} {{ testresult.written_by.number }}</span><br>
        {% if percentage != None %}
        Egzamin rozpoczęto <span class="str">{{ protocol.test_start_on }}</span> zakończono <span class="str">{{ protocol.test_end_on }}</span><br>
        Uzyskano <span class="str">{{ protocol.score }}</span> punktów z <span class="str">{{ protocol.max_score }}</span> możliwych (<span class="str">{{ percentage }}%</span> poprawnych)<br>
        {% else %}
            <span class="str">Egzamin został anulowany podczas zdawania przez prowadzącego.</span><br>
        {% endif %}
        
        Zdawano test <span class="str">{{ exam.test.name }}</span>
    </p>
    
    <hr>
    <h1>Zasady rozliczenia:</h1>
    <p>
        dostateczny (3): od <span class="str">{{ exam.test.g3_starts_at }}%</span> do <span class="str">{{ exam.test.g35_starts_at }}%</span><br>
        dostateczny + (3,5): od <span class="str">{{ exam.test.g35_starts_at }}%</span> do <span class="str">{{ exam.test.g4_starts_at }}%</span><br>
        dobry (4): od <span class="str">{{ exam.test.g4_starts_at }}%</span> do <span class="str">{{ exam.test.g45_starts_at }}%</span><br>
        dobry + (4,5): od <span class="str">{{ exam.test.g45_starts_at }}%</span> do <span class="str">{{ exam.test.g5_starts_at }}%</span><br>
        bardzo dobry (5): od <span class="str">{{ exam.test.g5_starts_at }}%</span> do <span class="str">100%</span><br>
        
    </p>
    
    {% if percentage != None %}
    <hr>

    <h1>Pytania i udzielone odpowiedzi:</h1>
    <div class="sepa">
        {% for questiontext, points, answers, pts_gained, question_id, attachment_url in protocol.questions %}
        <span class="str">{{ questiontext }}</span><br>
        <span class="footnote">{{ points }} punktów do zdobycia. Zdobyto {{ pts_gained }} punktów.</span><br>
        {% if attachment_url %}
        Załącznik:<br>
        <img src="{{ attachment_url }}" style="width: 400px;"><br>
        {% endif %}
        <div class="answers">
            {% for studanswer, realanswer, text, answer_id in answers %}
                {{ text }}<br>
                <span class="footnote">Udzielono odpowiedzi {% if studanswer %}TAK{% else %}NIE{% endif %}, poprawna to {% if realanswer %}TAK{% else %}NIE{% endif %}</span>
                <br>
            {% endfor %}
        </div>
        {% endfor %}
    </div>        
    {% endif %}
</body>
</html>

templates/rteacher/term_setup.html
{% extends "base-layout.html" %}

{% block layout_head %}
<style type="text/css">
    th { font-weight: bold; }
    table { text-align: center; margin-bottom: 20px; }
    td, th { padding-right: 10px; }
    .listhdr { width: 100%; text-align: center; font-weight: bold; }
    #fastlookup { width: 99%; height: 18px; line-height: 18px;}
    .student { width: 100%; height: 20px; line-height: 20px; border: 1px solid black; background: lightgray; text-align: center; cursor: pointer; }
        .student span { display: inline-block; }
        .student .name { width: 25%; }
        .student .surname { width: 35%; }
        .student .number { width: 30%; }
    #accept {
        width: 100%;
        height: 20px;
        line-height: 20px;
        border: 1px solid black;
        background: green;
        text-align: center;
        cursor: pointer;
        font-weight: bold;
    }
</style>
<script type="text/javascript">
    function matches(name, surname, number, chunk) {
        if (chunk == '') return true;
        name = String(name).search(chunk) > -1;
        surname = String(surname).search(chunk) > -1;
        number = String(number).search(chunk) > -1;
        return (name || surname || number);
    }

    function student_selected(studentid) {
        var studobj = $('#student'+studentid).attr('onclick', '').unbind('click').detach().click(function() { student_unselected(studentid); });
        $('#students_selected').append(studobj);
    }

    function student_unselected(studentid) {
        var studobj = $('#student'+studentid).unbind('click').detach().click(function() { student_selected(studentid); });
        $('#students_to_select').append(studobj);
    }

    $(function () {
        $('#fastlookup').keyup(function() {
            var chunk = String($('#fastlookup').val()).trim();
            var students = $('#students_to_select .student');
            for (var i=0; i<students.length; i++) {
                var student = students[i];
                if (matches($('#'+student.id+' .name').html(),
                            $('#'+student.id+' .surname').html(),
                            $('#'+student.id+' .number').html(),
                            chunk)) {
                    $(student).css('display', 'block');
                } else {
                    $(student).css('display', 'none');
                }
            }
        }).click(function() {
            if ($('#fastlookup').val() == 'Filtruj listę: wpisz imię, nazwisko, numer... (wyszukiwanie)')
                $('#fastlookup').val('');
        });
        $('#accept').click(function() {
            if (!confirm('Czy na pewno rozpocząć egzamin?')) return;
            var students = $('#students_selected .student');
            var studs = new Array();
            for (var i=0; i<students.length; i++) {
                var stud = students[i];
                if (stud.id.indexOf('student') != 0) return;
                realid = parseInt(stud.id.slice(7));
                studs.push(realid);
            }
            $.post('/teacher/exams/{{ term.exam.id }}/terms/{{ term.id }}/setup/ajax/', {
                "students": JSON.stringify(studs)
            }, function() {
                window.location = '/teacher/exams/{{ term.exam.id }}/terms/{{ term.id }}/supervise/';
            });
        });
    });
</script>
{% endblock %}

{% block layout_entries %}
    <li><a href="/profile/">Profil</a></li>
    <li><a href="/teacher/groups/">Grupy</a></li>
    <li class="current"><a href="/teacher/exams/">Egzaminy</a></li>
    <li><a href="/teacher/tests/">Baza testów</a></li>
{% endblock %}

{% block title %}Ustawianie terminu - {{ exam.name }}{% endblock %}

{% block layout_content %}
    {% if exam %}
        <h1><a href="/teacher/exams/{{ exam.id }}/">{{ exam.name }}</a></h1>
        <h1>Termin: <a href="/teacher/exams/{{ exam.id }}/terms/{{ term.id }}/">{{ term.name }}</a></h1>
        <div style="margin-top: 20px; font-size: 1.5em; text-align: center;">Wybierz studentów którzy piszą ten termin</div>
        <hr>
    {% endif %}

<div id="base_leftside">
    <div class="listhdr">Studenci których możesz wybrać (kliknij na studenta)</div>
    <input id="fastlookup" value="Filtruj listę: wpisz imię, nazwisko, numer... (wyszukiwanie)">
    <div id="students_to_select">
        {% for student in students %}
        <div class="student" id="student{{ student.id }}" onclick="student_selected({{ student.id }})">
            <span class="name">{{ student.name }}</span>
            <span class="surname">{{ student.surname }}</span>
            <span class="number">{{ student.number }}</span>    
        </div>
        {% endfor %}
    </div>
</div>
<div id="base_rightside">
    <div class="listhdr">Wybrani studenci (kliknij by usunąć)</div>
    <div id="accept">Kliknij tu by rozpocząć egzamin</div>
    <div id="students_selected">
    </div>        
</div>
{% endblock %}

templates/rteacher/tests_add.html
{% extends "base-layout.html" %}

{% block title %}Dodaj nowy test{% endblock %}

{% block layout_head %}
<style type="text/css">
    h1 { font-size: 1.5em; margin-bottom: 3px; }
    form { margin: 10px 0px 20px 30px;}
    form label { width: 250px; display: inline-block; }
    .errorlist { margin-left: 10px; color: red; font-weight: bold;}
</style>
<script type="text/javascript">
    $(function() {
        $('#id_is_time_per_question').change(function() {
            if ($('#id_is_time_per_question').is(':checked'))
                $('#id_time').attr('disabled', 'disabled').val('');
            else
                $('#id_time').removeAttr('disabled');
        })
    });
</script>
{% endblock %}

{% block layout_entries %}
    <li><a href="/profile/">Profil</a></li>
    <li><a href="/teacher/groups/">Grupy</a></li>
    <li><a href="/teacher/exams/">Egzaminy</a></li>
    <li class="current"><a href="/teacher/tests/">Baza testów</a></li>
{% endblock %}

{% block layout_content %}
    <h1>Utwórz nowy test</h1>
    <form action="/teacher/tests/create/" method="post">
        {{ form.as_p }}
        <input type="submit" value="Utwórz">
    </form>

{% endblock %}

templates/rteacher/tests_category_add.html
{% extends "rteacher/tests_test.html" %}

{% block title %}Dodaj nową kategorię{% endblock %}

{% block layout_rightside %}
    <h1>Utwórz nową kategorię</h1>
    <form action="/teacher/tests/{{ test.id }}/category/create/" method="post">
        {{ form.as_p }}
        <input type="submit" value="Utwórz">
    </form>

{% endblock %}