urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', 'athena.front.index.index'),
    url(r'^about/$', 'athena.front.index.about'),
    url(r'^register/$', 'athena.users.views.register'),
    url(r'^logout/$', 'athena.users.views.logout'),
    url(r'^admin-login/$', 'athena.radmin.login_view.login'),
    url(r'^profile/$', 'athena.users.views.profile'),
    url(r'^login/$', 'athena.users.views.login'),
    url(r'^login/demo/$', 'athena.users.views.demo'),

    (r'^media/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': 'D:/projects/athena/media/'}),  
    (r'^uploads/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': 'D:/projects/athena/uploads/'}),  
)

urlpatterns += patterns('athena.rstudent',
    url(r'^demo/start/(?P<test_id>\d+)/$', 'demo.start_demo_exam'),
    url(r'^past/$', 'protocol.index'),
    url(r'^past/(?P<protocol_id>\d+)/$', 'protocol.index'),
    url(r'^groups/$', 'views.groups'),
    url(r'^groups/join/$', 'views.join_group'),    
)

urlpatterns += patterns('athena.tests',
    url(r'^test/ajax/$', 'views.ajax'),
    url(r'^test/$', 'views.test'),
)

urlpatterns += patterns('athena.rteacher',

    url(r'^teacher/groups/$', 'manage_groups.list'),
    url(r'^teacher/groups/(?P<group_id>\d+)/$', 'manage_groups.group'),
    url(r'^teacher/groups/(?P<group_id>\d+)/members/$', 'manage_groups.members'),
    url(r'^teacher/groups/(?P<group_id>\d+)/requests/$', 'manage_groups.requests'),
    url(r'^teacher/groups/create/$', 'manage_groups.create'),

        # must be called with POST to actually succeed. Calling with GET will result in HTTP 400
    url(r'^teacher/groups/(?P<group_id>\d+)/delete/$', 'manage_groups.delete'),

    url(r'^teacher/exams/protocol/(?P<testresult_id>\d+)/$', 'term_supervise.protocol'),
    url(r'^teacher/exams/(?P<exam_id>\d+)/terms/(?P<term_id>\d+)/supervise/$', 'term_supervise.supervise'),
    url(r'^teacher/exams/(?P<exam_id>\d+)/terms/(?P<term_id>\d+)/supervise/ajax/$', 'term_supervise.ajax'),
    url(r'^teacher/exams/(?P<exam_id>\d+)/terms/(?P<term_id>\d+)/setup/ajax/$', 'term_setup.setup_ajax'),
    url(r'^teacher/exams/(?P<exam_id>\d+)/terms/(?P<term_id>\d+)/setup/$', 'term_setup.setup'),
    url(r'^teacher/exams/(?P<exam_id>\d+)/terms/(?P<term_id>\d+)/delete/$', 'manage_exams.delete_term'),
    url(r'^teacher/exams/(?P<exam_id>\d+)/terms/(?P<term_id>\d+)/$', 'manage_exams.term'),
    url(r'^teacher/exams/table/(?P<exam_id>\d+)/$', 'gentable.gentable'),
    url(r'^teacher/exams/$', 'manage_exams.list'),
    url(r'^teacher/exams/create/$', 'manage_exams.create'),
    url(r'^teacher/exams/(?P<exam_id>\d+)/$', 'manage_exams.exam'),
    url(r'^teacher/exams/(?P<exam_id>\d+)/addterm/$', 'manage_exams.addterm'),

        # must be called with POST to actually succeed. Calling with GET will result in HTTP 400
    url(r'^teacher/exams/(?P<exam_id>\d+)/delete/$', 'manage_exams.delete'),

    url(r'^teacher/tests/$', 'tests.list'),
    url(r'^teacher/tests/create/$', 'tests.create'),
    url(r'^teacher/tests/(?P<test_id>\d+)/$', 'tests.test'),
    url(r'^teacher/tests/(?P<test_id>\d+)/delete/$', 'tests.delete_test'),
    url(r'^teacher/tests/(?P<test_id>\d+)/ajax/$', 'tests.test_ajax'),
    url(r'^teacher/tests/(?P<test_id>\d+)/category/create/$', 'tests.create_category'),
    url(r'^teacher/tests/(?P<test_id>\d+)/category/(?P<category_id>\d+)/$', 'tests.category'),
    url(r'^teacher/tests/(?P<test_id>\d+)/category/(?P<category_id>\d+)/delete/$', 'tests.delete_category'),

    url(r'^teacher/tests/(?P<test_id>\d+)/category/(?P<category_id>\d+)/question/new/$', 'tests.create_question'),
    url(r'^teacher/tests/(?P<test_id>\d+)/category/(?P<category_id>\d+)/question/(?P<question_id>\d+)/$', 'tests.question'),
)


urlpatterns += patterns('athena.radmin',

    url(r'^admin/accounts/$', 'manage_accounts.list'),
    url(r'^admin/accounts/(?P<account_id>\d+)/$', 'manage_accounts.account'),

    url(r'^admin/accounts/create/$', 'manage_accounts.create'),

    url(r'^admin/accounts/students/$', 'manage_accounts.view_students'),
    url(r'^admin/accounts/students/(?P<page>\d+)/$', 'manage_accounts.view_students'),

        # must be called with POST to actually succeed. Calling with GET will result in HTTP 400
    url(r'^admin/accounts/(?P<account_id>\d+)/delete/$', 'manage_accounts.delete'),
    url(r'^admin/accounts/(?P<account_id>\d+)/reset_pwd/$', 'manage_accounts.reset_pwd'),
    url(r'^admin/accounts/(?P<account_id>\d+)/su/$', 'manage_accounts.su'),
)

users/models.py
# coding=UTF-8
from django.db import models
from hashlib import sha1

USER_STATUS = (
    (0, u'Student'),
    (1, u'Nauczyciel'),
    (2, u'Administrator'),
)

class User(models.Model):
    name = models.TextField(blank=True, verbose_name=u'Imię')
    surname = models.TextField(blank=True, verbose_name=u'Nazwisko')

    login = models.EmailField(max_length=254, db_index=True)        # also an email
    password = models.CharField(max_length=40, default='')  # computed as SHA1(login+password in utf).hexdigest()

    status = models.IntegerField(choices=USER_STATUS, default=0)

    number = models.IntegerField(null=True, blank=True, verbose_name=u'Nr albumu')

    created_on = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['login']

    def is_demo(self):
        """Returns whether this is a demo student or a 'baseline' account teacher"""
        return self.login.split('@')[1] == 'demo.athena'
    
    def does_password_match(self, pwd):
        """Checks whether supplied password matches this account's password"""
        y = sha1(self.login.encode('utf8')+pwd.encode('utf8')).hexdigest()
        return self.password == y

    def set_password(self, newpwd):
        """Saves this instance"""
        self.password = sha1(self.login.encode('utf8')+newpwd.encode('utf8')).hexdigest()
        self.save()

radmin/views.py
from athena.users import must_be_admin
from athena.core import render_to_response

@must_be_admin
def index(request):
    return render_to_response('radmin/index.html', request)

users/views.py
# coding=UTF-8
from django import forms
from athena.users.models import User
from athena.rteacher.models import Group
from django.contrib import messages
from django.shortcuts import redirect
from athena.core import render_to_response
from athena.users import must_be_logged, must_not_be_logged
from datetime import datetime, timedelta
from random import randint

@must_be_logged
def profile(request):
    
    class ProfileForm(forms.ModelForm):
        class Meta:
            model = User
            
    class ChangePasswordForm(forms.Form):
        current_pwd = forms.CharField(widget=forms.PasswordInput, label=u'Aktualne hasło')
        new_pwd = forms.CharField(widget=forms.PasswordInput, label=u'Nowe hasło')
        new_pwd2 = forms.CharField(widget=forms.PasswordInput, label=u'Potwierdź nowe')
    
        def __init__(self, request, *args, **kwargs):
            super(ChangePasswordForm, self).__init__(*args, **kwargs)
            self.user = request.user
    
        def clean(self):
            cleaned_data = super(ChangePasswordForm, self).clean()
            if not self.user.does_password_match(cleaned_data['current_pwd']):
                raise forms.ValidationError(u'Błędne hasło aktualne')
            
            if cleaned_data['new_pwd'] != cleaned_data['new_pwd2']:
                raise forms.ValidationError(u'Hasła nie zgadzają się!')
                
            return cleaned_data

    if request.method == 'POST':
        cpf = ChangePasswordForm(request, request.POST)
        if cpf.is_valid():
            request.user.set_password(cpf.cleaned_data['new_pwd'])
            messages.add_message(request, messages.SUCCESS, u'Hasło zmienione.')
    else:
        cpf = ChangePasswordForm(request)
    
    return render_to_response('profile.html', request, cpf=cpf)

@must_not_be_logged
def demo(request):
    """Logs in a demo user"""
    # Check if it's possible to login
    if User.objects.filter(login__endswith='@demo.athena').count() > 1000:
        
        # Attempt to remove superficial accounts
        k = User.objects.filter(status=1, login__endswith='@demo.athena') \
                        .filter(created_on__lt=datetime.now() - timedelta(1))
        for x in k: x.delete()
            
        if User.objects.filter(login__endswith='@demo.athena').count() > 1000:
            messages.add_message(request, messages.ERROR, u'Błąd: przeciążenie systemu')
            return redirect('/')
    
    target_login = '%s@demo.athena' % (randint(0, 10000000))
        
    su = User(name='Tymczasowe konto DEMO', surname='', login=target_login, number=0)
    su.save()
    Group.get_demo_group().students.add(su)

    request.login(target_login)
    
    messages.add_message(request, messages.INFO, u'Zalogowano demonstracyjnie.')

    return redirect('/')
    
@must_not_be_logged    
def login(request):
    """Handles logging in"""

    class LoginForm(forms.Form):

        login = forms.EmailField(max_length=254, label=u'Email')
        password = forms.CharField(widget=forms.PasswordInput, label=u'Hasło', required=True)

        def clean(self):
            cleaned_data = super(LoginForm, self).clean()

            login, password = cleaned_data.get('login'), cleaned_data.get('password')

            if not login: return cleaned_data
            if not password: return cleaned_data

            try:
                usr = User.objects.get(login=login)
            except User.DoesNotExist:
                raise forms.ValidationError(u'Nie ma takiego użytkownika')

            if not usr.does_password_match(password):
                raise forms.ValidationError(u'Błędne hasło')

            if usr.status > 0:
                raise forms.ValidationError(u'Logowanie zabronione')

            return cleaned_data

    if request.method == 'POST':
        rf = LoginForm(request.POST)

        if rf.is_valid():
            request.login(rf.cleaned_data['login'])      # Log in the user

            messages.add_message(request, messages.SUCCESS, u'Zalogowano.')
            return redirect('/')
    else:
        rf = LoginForm()

    return render_to_response('front/login.html', request, form=rf)    

#=======================================================================================
@must_not_be_logged
def register(request):
    """Handles registering new students only"""

    class RegisterForm(forms.Form):

        name = forms.CharField(label=u'Imię')
        surname = forms.CharField(label=u'Nazwisko')

        login = forms.EmailField(max_length=254, label=u'Email')

        album = forms.IntegerField(label=u'Nr albumu')

        password = forms.CharField(widget=forms.PasswordInput, label=u'Hasło', required=True)
        password2 = forms.CharField(widget=forms.PasswordInput, label=u'Powtórz hasło', required=True)


        def clean_login(self):
            """Assure login is unique"""
            lgn = self.cleaned_data['login']
            try:
                usr = User.objects.get(login=lgn)
            except User.DoesNotExist:
                return lgn
            raise forms.ValidationError(u'Taki e-mail jest już używany!')

        def clean(self):
            """Assure passwords match"""
            cleaned_data = super(RegisterForm, self).clean()

            pwd1 = cleaned_data.get('password')
            pwd2 = cleaned_data.get('password2')

            if pwd1 != pwd2:
                self._errors['password'] = self.error_class(['Niezgodne hasła'])
                self._errors['password2'] = self.error_class(['Niezgodne hasła'])

                del cleaned_data['password']
                del cleaned_data['password2']

            return cleaned_data


    if request.method == 'POST':
        rf = RegisterForm(request.POST)

        if rf.is_valid():

            # Create an account
            u = User(name=rf.cleaned_data['name'],
                     surname=rf.cleaned_data['surname'],
                     login=rf.cleaned_data['login'],
                     number=rf.cleaned_data['album'])
            u.save()
            u.set_password(rf.cleaned_data['password'])

            request.login(u.login)      # Log in the user

            messages.add_message(request, messages.INFO, u'Utworzono nowe konto. Zostałeś zalogowany.')
            return redirect('/')
    else:
        rf = RegisterForm()

    return render_to_response('front/register.html', request, form=rf)

#=======================================================================================
@must_be_logged
def logout(request):
    """Handles logging out"""
    if request.user:
        request.logout()
        messages.add_message(request, messages.INFO, u'Wylogowano.')
    
    return redirect('/')

templates/radmin/index.html
{% extends "base-layout.html" %}

{% block title %}Panel administratora{% endblock %}

{% block layout_entries %}
    <li><a href="/profile/">Profil</a></li>
    <li><a href="/admin/accounts/">Konta</a></li>
{% endblock %}

{% block layout_content %}
    <h1>Panel administratora</h1>

    <p>
        Jesteś zalogowany jako administrator. Z tej pozycji możesz zarządzać kontami. Tylko administrator może tworzyć nowe konta administratorów i nauczycieli. Możesz także zarządzać kontami studentów - zmieniać niektóre ich dane oraz usuwać te konta. Administrator może też zalogować się jako dowolny użytkownik, przy wykorzystaniu odpowiedniej opcji. Szczególnie jako administrator pamiętaj o <a href="/logout/">wylogowaniu się</a> po zakończonej pracy.
    </p>
    <p>
        Swoje hasło możesz zmienić w zakładce <a href="/profile/">Profil</a>.
    </p>

{% endblock %}

templates/radmin/manage_accounts_acc.html
{% extends "radmin/manage_accounts_list.html" %}

{% block title %}Zarządzanie - {{ account.login }}{% endblock %}

{% block layout_rightside %}
<form action="/admin/accounts/{{ account.id }}/" method="post">
    <p>
        <label for="id_login">Login:</label>
        <input type="text" name="login" id="id_login" value="{{ account.login }}" disabled>
    </p>
    <p>
        <label for="id_status">Status:</label>
        <input type="text" name="login" id="id_login" value="{% if account.status == 0 %}Student{% elif account.status == 1 %}Nauczyciel{% elif account.status == 2 %}Administrator{% else %}Nieznany{% endif %}" disabled>
    </p>
    {{ form.as_p }}
    <input type="submit" value="Zapisz">
</form>

<form action="/admin/accounts/{{ account.id }}/delete/" method="post" class="standalone-button">
    <input type="submit" value="Usuń konto">
</form>
<form action="/admin/accounts/{{ account.id }}/reset_pwd/" method="post" class="standalone-button">
    <input type="submit" value="Resetuj hasło">
</form>
<form action="/admin/accounts/{{ account.id }}/su/" method="post" class="standalone-button">
    <input type="submit" value="Zaloguj jako ten użytkownik">
</form>
{% endblock %}

templates/radmin/manage_accounts_add.html
{% extends "radmin/manage_accounts_list.html" %}

{% block layout_rightside %}
    <h1>Utwórz nowe konto</h1>
    <form action="/admin/accounts/create/" method="post">
        {{ form.as_p }}
        <input type="submit" value="Utwórz">
    </form>
{% endblock %}

templates/radmin/manage_accounts_list.html
{% extends "base-layout.html" %}

{# root page for students #}

{% block title %}Strona główna{% endblock %}

{% block layout_head %}
<style type="text/css">
    h1 { font-size: 1.5em; margin-bottom: 3px; }
    p { text-align: justify; margin-left: 30px; }
</style>
{% endblock %}

{% block layout_entries %}
    <li><a href="/profile/">Profil</a></li>
    <li class="current"><a href="/admin/accounts/">Konta</a></li>
{% endblock %}

{% block layout_content %}
<div id="base_leftside">
    {% if selected_user_id == 'create' %}
        Dodaj nowe konto
    {% else %}
        <a href="/admin/accounts/create/">Dodaj nowe konto</a>
    {% endif %}

    <h1 style="margin-top: 20px;">Administratorzy</h1>
    <p>
        {% for account in admins %}
            {% if account.id == selected_user_id %}
                {{ account.login }} : {{ account.name }} {{ account.surname }}
            {% else %}
            <a href="/admin/accounts/{{ account.id }}/">{{ account.login }} : {{ account.name }} {{ account.surname }}</a> 
            {% endif %}<br>
        {% empty %}
            brak
        {% endfor %}
    </p>
    <h1>Nauczyciele</h1>
    <p>
        {% for account in teachers %}
            {% if account.id == selected_user_id %}
                {{ account.login }} : {{ account.name }} {{ account.surname }}
            {% else %}
            <a href="/admin/accounts/{{ account.id }}/">{{ account.login }} : {{ account.name }} {{ account.surname }}</a> 
            {% endif %} <br>           
        {% empty %}
            brak
        {% endfor %}
    </p>
    <h1>Studenci</h1>
    <p>
        <a href="/admin/accounts/students/">...więcej...</a>
    </p>
    <div style="margin-bottom: 20px;"></div>
</div>
<div id="base_rightside">
    {% block layout_rightside %}{% endblock %}
</div>
{% endblock %}

templates/radmin/manage_accounts_students_acc.html
{% extends "radmin/manage_accounts_students_list.html" %}

{% block title %}Zarządzanie - {{ account.login }}{% endblock %}

{% block layout_rightside %}
<form action="/admin/accounts/{{ account.id }}/" method="post">
    <p>
        <label for="id_login">Login:</label>
        <input type="text" name="login" id="id_login" value="{{ account.login }}" disabled>
    </p>
    <p>
        <label for="id_status">Status:</label>
        <input type="text" name="login" id="id_login" value="Student" disabled>
    </p>
    {{ form.as_p }}
    <input type="submit" value="Zaloguj">
</form>

<form action="/admin/accounts/{{ account.id }}/delete/" method="post" class="standalone-button">
    <input type="submit" value="Usuń konto">
</form>
<form action="/admin/accounts/{{ account.id }}/reset_pwd/" method="post" class="standalone-button">
    <input type="submit" value="Resetuj hasło">
</form>
<form action="/admin/accounts/{{ account.id }}/su/" method="post" class="standalone-button">
    <input type="submit" value="Zaloguj jako ten użytkownik">
</form>
{% endblock %}

templates/radmin/manage_accounts_students_list.html
{% extends "base-layout.html" %}

{# root page for students #}

{% block title %}Strona główna{% endblock %}

{% block layout_head %}
<style type="text/css">
    h1 { font-size: 1.5em; margin-bottom: 3px; }
    p { text-align: justify; margin-left: 30px; }
    .pages { text-align: center; margin-top: 10px; }
</style>
{% endblock %}

{% block layout_entries %}
    <li><a href="/profile/">Profil</a></li>
    <li class="current"><a href="/admin/accounts/">Konta</a></li>
{% endblock %}

{% block layout_content %}
<div id="base_leftside">
    <h1 style="margin-top: 20px;">Studenci</h1>
    <p>
        {% for account in page.object_list %}
            {% if account.id == selected_user_id %}
                {{ account.login }} : {{ account.name }} {{ account.surname }}
            {% else %}
            <a href="/admin/accounts/{{ account.id }}/">{{ account.login }} : {{ account.name }} {{ account.surname }}</a> <br>
            {% endif %}
        {% empty %}
            brak
        {% endfor %}
    </p>
    <div class="pages">
        {% if page.has_previous %}
            <a href="/admin/accounts/students/{{ page.previous_page_number }}/">{{ page.previous_page_number }}</a> | 
        {% endif %}
            {{ page.number }}
        {% if page.has_next %}
            | <a href="/admin/accounts/students/{{ page.next_page_number }}/">{{ page.next_page_number }}</a>
        {% endif %}
    </div>
    <div style="margin-bottom: 20px;"></div>
</div>
<div id="base_rightside">
    {% block layout_rightside %}{% endblock %}
</div>
{% endblock %}